[package]
name = "wasmtime_write"
version = "0.1.0"
edition = "2021"
# build = "../../build_user.rs"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
ms_std = { path = "../../ms_std", features = ["panic_def", "alloc_def"] }
ms_hostcall = { path = "../../ms_hostcall" }
wasmtime_wasi_api = { path = "../../wasmtime_wasi_api" }

# wasmtime = { version = "=21.0.0", default-features = false, features = [
#     "runtime",
#     "gc",
#     "component-model",
# ] }


[features]
mpk = ["ms_std/mpk"]

default = []
